/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AccountNumbersRouteImport } from './routes/account-numbers'
import { Route as AddCashRouteImport } from './routes/add-cash'
import { Route as AddDebitCardRouteImport } from './routes/add-debit-card'
import { Route as ApplePayRouteImport } from './routes/apple-pay'
import { Route as CashbackRouteImport } from './routes/cashback'
import { Route as DepositCheckRouteImport } from './routes/deposit-check'
import { Route as DirectDepositRouteImport } from './routes/direct-deposit'
import { Route as FundAppsRouteImport } from './routes/fund-apps'
import { Route as FundInstantlyRouteImport } from './routes/fund-instantly'
import { Route as LinkedCardsRouteImport } from './routes/linked-cards'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ManageCardsRouteImport } from './routes/manage-cards'
import { Route as MoveMoneyRouteImport } from './routes/move-money'
import { Route as MyVaroRouteImport } from './routes/my-varo'
import { Route as NotificationSettingsRouteImport } from './routes/notification-settings'
import { Route as PayBillsRouteImport } from './routes/pay-bills'
import { Route as PersonalDetailsRouteImport } from './routes/personal-details'
import { Route as SavingsRouteImport } from './routes/savings'
import { Route as SendMoneyRouteImport } from './routes/send-money'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SplashRouteImport } from './routes/splash'
import { Route as TransferRouteImport } from './routes/transfer'
import { Route as VaroCardsRouteImport } from './routes/varo-cards'
import { Route as ZelleRouteImport } from './routes/zelle'
import { Route as TransactionIdRouteImport } from './routes/transaction.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountNumbersRoute = AccountNumbersRouteImport.update({
  id: '/account-numbers',
  path: '/account-numbers',
  getParentRoute: () => rootRouteImport,
} as any)
const AddCashRoute = AddCashRouteImport.update({
  id: '/add-cash',
  path: '/add-cash',
  getParentRoute: () => rootRouteImport,
} as any)
const AddDebitCardRoute = AddDebitCardRouteImport.update({
  id: '/add-debit-card',
  path: '/add-debit-card',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplePayRoute = ApplePayRouteImport.update({
  id: '/apple-pay',
  path: '/apple-pay',
  getParentRoute: () => rootRouteImport,
} as any)
const CashbackRoute = CashbackRouteImport.update({
  id: '/cashback',
  path: '/cashback',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositCheckRoute = DepositCheckRouteImport.update({
  id: '/deposit-check',
  path: '/deposit-check',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectDepositRoute = DirectDepositRouteImport.update({
  id: '/direct-deposit',
  path: '/direct-deposit',
  getParentRoute: () => rootRouteImport,
} as any)
const FundAppsRoute = FundAppsRouteImport.update({
  id: '/fund-apps',
  path: '/fund-apps',
  getParentRoute: () => rootRouteImport,
} as any)
const FundInstantlyRoute = FundInstantlyRouteImport.update({
  id: '/fund-instantly',
  path: '/fund-instantly',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkedCardsRoute = LinkedCardsRouteImport.update({
  id: '/linked-cards',
  path: '/linked-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageCardsRoute = ManageCardsRouteImport.update({
  id: '/manage-cards',
  path: '/manage-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const MoveMoneyRoute = MoveMoneyRouteImport.update({
  id: '/move-money',
  path: '/move-money',
  getParentRoute: () => rootRouteImport,
} as any)
const MyVaroRoute = MyVaroRouteImport.update({
  id: '/my-varo',
  path: '/my-varo',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationSettingsRoute = NotificationSettingsRouteImport.update({
  id: '/notification-settings',
  path: '/notification-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PayBillsRoute = PayBillsRouteImport.update({
  id: '/pay-bills',
  path: '/pay-bills',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalDetailsRoute = PersonalDetailsRouteImport.update({
  id: '/personal-details',
  path: '/personal-details',
  getParentRoute: () => rootRouteImport,
} as any)
const SavingsRoute = SavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => rootRouteImport,
} as any)
const SendMoneyRoute = SendMoneyRouteImport.update({
  id: '/send-money',
  path: '/send-money',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SplashRoute = SplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const TransferRoute = TransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const VaroCardsRoute = VaroCardsRouteImport.update({
  id: '/varo-cards',
  path: '/varo-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const ZelleRoute = ZelleRouteImport.update({
  id: '/zelle',
  path: '/zelle',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionIdRoute = TransactionIdRouteImport.update({
  id: '/transaction/$id',
  path: '/transaction/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/account-numbers': typeof AccountNumbersRoute
  '/add-cash': typeof AddCashRoute
  '/add-debit-card': typeof AddDebitCardRoute
  '/apple-pay': typeof ApplePayRoute
  '/cashback': typeof CashbackRoute
  '/deposit-check': typeof DepositCheckRoute
  '/direct-deposit': typeof DirectDepositRoute
  '/fund-apps': typeof FundAppsRoute
  '/fund-instantly': typeof FundInstantlyRoute
  '/linked-cards': typeof LinkedCardsRoute
  '/login': typeof LoginRoute
  '/manage-cards': typeof ManageCardsRoute
  '/move-money': typeof MoveMoneyRoute
  '/my-varo': typeof MyVaroRoute
  '/notification-settings': typeof NotificationSettingsRoute
  '/pay-bills': typeof PayBillsRoute
  '/personal-details': typeof PersonalDetailsRoute
  '/savings': typeof SavingsRoute
  '/send-money': typeof SendMoneyRoute
  '/signup': typeof SignupRoute
  '/splash': typeof SplashRoute
  '/transfer': typeof TransferRoute
  '/varo-cards': typeof VaroCardsRoute
  '/zelle': typeof ZelleRoute
  '/transaction/$id': typeof TransactionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/account-numbers': typeof AccountNumbersRoute
  '/add-cash': typeof AddCashRoute
  '/add-debit-card': typeof AddDebitCardRoute
  '/apple-pay': typeof ApplePayRoute
  '/cashback': typeof CashbackRoute
  '/deposit-check': typeof DepositCheckRoute
  '/direct-deposit': typeof DirectDepositRoute
  '/fund-apps': typeof FundAppsRoute
  '/fund-instantly': typeof FundInstantlyRoute
  '/linked-cards': typeof LinkedCardsRoute
  '/login': typeof LoginRoute
  '/manage-cards': typeof ManageCardsRoute
  '/move-money': typeof MoveMoneyRoute
  '/my-varo': typeof MyVaroRoute
  '/notification-settings': typeof NotificationSettingsRoute
  '/pay-bills': typeof PayBillsRoute
  '/personal-details': typeof PersonalDetailsRoute
  '/savings': typeof SavingsRoute
  '/send-money': typeof SendMoneyRoute
  '/signup': typeof SignupRoute
  '/splash': typeof SplashRoute
  '/transfer': typeof TransferRoute
  '/varo-cards': typeof VaroCardsRoute
  '/zelle': typeof ZelleRoute
  '/transaction/$id': typeof TransactionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/account-numbers': typeof AccountNumbersRoute
  '/add-cash': typeof AddCashRoute
  '/add-debit-card': typeof AddDebitCardRoute
  '/apple-pay': typeof ApplePayRoute
  '/cashback': typeof CashbackRoute
  '/deposit-check': typeof DepositCheckRoute
  '/direct-deposit': typeof DirectDepositRoute
  '/fund-apps': typeof FundAppsRoute
  '/fund-instantly': typeof FundInstantlyRoute
  '/linked-cards': typeof LinkedCardsRoute
  '/login': typeof LoginRoute
  '/manage-cards': typeof ManageCardsRoute
  '/move-money': typeof MoveMoneyRoute
  '/my-varo': typeof MyVaroRoute
  '/notification-settings': typeof NotificationSettingsRoute
  '/pay-bills': typeof PayBillsRoute
  '/personal-details': typeof PersonalDetailsRoute
  '/savings': typeof SavingsRoute
  '/send-money': typeof SendMoneyRoute
  '/signup': typeof SignupRoute
  '/splash': typeof SplashRoute
  '/transfer': typeof TransferRoute
  '/varo-cards': typeof VaroCardsRoute
  '/zelle': typeof ZelleRoute
  '/transaction/$id': typeof TransactionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/account-numbers'
    | '/add-cash'
    | '/add-debit-card'
    | '/apple-pay'
    | '/cashback'
    | '/deposit-check'
    | '/direct-deposit'
    | '/fund-apps'
    | '/fund-instantly'
    | '/linked-cards'
    | '/login'
    | '/manage-cards'
    | '/move-money'
    | '/my-varo'
    | '/notification-settings'
    | '/pay-bills'
    | '/personal-details'
    | '/savings'
    | '/send-money'
    | '/signup'
    | '/splash'
    | '/transfer'
    | '/varo-cards'
    | '/zelle'
    | '/transaction/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/account-numbers'
    | '/add-cash'
    | '/add-debit-card'
    | '/apple-pay'
    | '/cashback'
    | '/deposit-check'
    | '/direct-deposit'
    | '/fund-apps'
    | '/fund-instantly'
    | '/linked-cards'
    | '/login'
    | '/manage-cards'
    | '/move-money'
    | '/my-varo'
    | '/notification-settings'
    | '/pay-bills'
    | '/personal-details'
    | '/savings'
    | '/send-money'
    | '/signup'
    | '/splash'
    | '/transfer'
    | '/varo-cards'
    | '/zelle'
    | '/transaction/$id'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/account-numbers'
    | '/add-cash'
    | '/add-debit-card'
    | '/apple-pay'
    | '/cashback'
    | '/deposit-check'
    | '/direct-deposit'
    | '/fund-apps'
    | '/fund-instantly'
    | '/linked-cards'
    | '/login'
    | '/manage-cards'
    | '/move-money'
    | '/my-varo'
    | '/notification-settings'
    | '/pay-bills'
    | '/personal-details'
    | '/savings'
    | '/send-money'
    | '/signup'
    | '/splash'
    | '/transfer'
    | '/varo-cards'
    | '/zelle'
    | '/transaction/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AccountNumbersRoute: typeof AccountNumbersRoute
  AddCashRoute: typeof AddCashRoute
  AddDebitCardRoute: typeof AddDebitCardRoute
  ApplePayRoute: typeof ApplePayRoute
  CashbackRoute: typeof CashbackRoute
  DepositCheckRoute: typeof DepositCheckRoute
  DirectDepositRoute: typeof DirectDepositRoute
  FundAppsRoute: typeof FundAppsRoute
  FundInstantlyRoute: typeof FundInstantlyRoute
  LinkedCardsRoute: typeof LinkedCardsRoute
  LoginRoute: typeof LoginRoute
  ManageCardsRoute: typeof ManageCardsRoute
  MoveMoneyRoute: typeof MoveMoneyRoute
  MyVaroRoute: typeof MyVaroRoute
  NotificationSettingsRoute: typeof NotificationSettingsRoute
  PayBillsRoute: typeof PayBillsRoute
  PersonalDetailsRoute: typeof PersonalDetailsRoute
  SavingsRoute: typeof SavingsRoute
  SendMoneyRoute: typeof SendMoneyRoute
  SignupRoute: typeof SignupRoute
  SplashRoute: typeof SplashRoute
  TransferRoute: typeof TransferRoute
  VaroCardsRoute: typeof VaroCardsRoute
  ZelleRoute: typeof ZelleRoute
  TransactionIdRoute: typeof TransactionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-numbers': {
      id: '/account-numbers'
      path: '/account-numbers'
      fullPath: '/account-numbers'
      preLoaderRoute: typeof AccountNumbersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-cash': {
      id: '/add-cash'
      path: '/add-cash'
      fullPath: '/add-cash'
      preLoaderRoute: typeof AddCashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-debit-card': {
      id: '/add-debit-card'
      path: '/add-debit-card'
      fullPath: '/add-debit-card'
      preLoaderRoute: typeof AddDebitCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apple-pay': {
      id: '/apple-pay'
      path: '/apple-pay'
      fullPath: '/apple-pay'
      preLoaderRoute: typeof ApplePayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cashback': {
      id: '/cashback'
      path: '/cashback'
      fullPath: '/cashback'
      preLoaderRoute: typeof CashbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposit-check': {
      id: '/deposit-check'
      path: '/deposit-check'
      fullPath: '/deposit-check'
      preLoaderRoute: typeof DepositCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/direct-deposit': {
      id: '/direct-deposit'
      path: '/direct-deposit'
      fullPath: '/direct-deposit'
      preLoaderRoute: typeof DirectDepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fund-apps': {
      id: '/fund-apps'
      path: '/fund-apps'
      fullPath: '/fund-apps'
      preLoaderRoute: typeof FundAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fund-instantly': {
      id: '/fund-instantly'
      path: '/fund-instantly'
      fullPath: '/fund-instantly'
      preLoaderRoute: typeof FundInstantlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linked-cards': {
      id: '/linked-cards'
      path: '/linked-cards'
      fullPath: '/linked-cards'
      preLoaderRoute: typeof LinkedCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage-cards': {
      id: '/manage-cards'
      path: '/manage-cards'
      fullPath: '/manage-cards'
      preLoaderRoute: typeof ManageCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/move-money': {
      id: '/move-money'
      path: '/move-money'
      fullPath: '/move-money'
      preLoaderRoute: typeof MoveMoneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-varo': {
      id: '/my-varo'
      path: '/my-varo'
      fullPath: '/my-varo'
      preLoaderRoute: typeof MyVaroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notification-settings': {
      id: '/notification-settings'
      path: '/notification-settings'
      fullPath: '/notification-settings'
      preLoaderRoute: typeof NotificationSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay-bills': {
      id: '/pay-bills'
      path: '/pay-bills'
      fullPath: '/pay-bills'
      preLoaderRoute: typeof PayBillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal-details': {
      id: '/personal-details'
      path: '/personal-details'
      fullPath: '/personal-details'
      preLoaderRoute: typeof PersonalDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/savings': {
      id: '/savings'
      path: '/savings'
      fullPath: '/savings'
      preLoaderRoute: typeof SavingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send-money': {
      id: '/send-money'
      path: '/send-money'
      fullPath: '/send-money'
      preLoaderRoute: typeof SendMoneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splash': {
      id: '/splash'
      path: '/splash'
      fullPath: '/splash'
      preLoaderRoute: typeof SplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfer': {
      id: '/transfer'
      path: '/transfer'
      fullPath: '/transfer'
      preLoaderRoute: typeof TransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/varo-cards': {
      id: '/varo-cards'
      path: '/varo-cards'
      fullPath: '/varo-cards'
      preLoaderRoute: typeof VaroCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zelle': {
      id: '/zelle'
      path: '/zelle'
      fullPath: '/zelle'
      preLoaderRoute: typeof ZelleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transaction/$id': {
      id: '/transaction/$id'
      path: '/transaction/$id'
      fullPath: '/transaction/$id'
      preLoaderRoute: typeof TransactionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AccountNumbersRoute: AccountNumbersRoute,
  AddCashRoute: AddCashRoute,
  AddDebitCardRoute: AddDebitCardRoute,
  ApplePayRoute: ApplePayRoute,
  CashbackRoute: CashbackRoute,
  DepositCheckRoute: DepositCheckRoute,
  DirectDepositRoute: DirectDepositRoute,
  FundAppsRoute: FundAppsRoute,
  FundInstantlyRoute: FundInstantlyRoute,
  LinkedCardsRoute: LinkedCardsRoute,
  LoginRoute: LoginRoute,
  ManageCardsRoute: ManageCardsRoute,
  MoveMoneyRoute: MoveMoneyRoute,
  MyVaroRoute: MyVaroRoute,
  NotificationSettingsRoute: NotificationSettingsRoute,
  PayBillsRoute: PayBillsRoute,
  PersonalDetailsRoute: PersonalDetailsRoute,
  SavingsRoute: SavingsRoute,
  SendMoneyRoute: SendMoneyRoute,
  SignupRoute: SignupRoute,
  SplashRoute: SplashRoute,
  TransferRoute: TransferRoute,
  VaroCardsRoute: VaroCardsRoute,
  ZelleRoute: ZelleRoute,
  TransactionIdRoute: TransactionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
